# Generated by Django 5.0.4 on 2024-04-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customdocument",
            name="bynder_id_hash",
        ),
        migrations.RemoveField(
            model_name="customdocument",
            name="bynder_original_filename",
        ),
        migrations.RemoveField(
            model_name="customdocument",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="customimage",
            name="bynder_id_hash",
        ),
        migrations.RemoveField(
            model_name="customimage",
            name="bynder_original_filename",
        ),
        migrations.RemoveField(
            model_name="customimage",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="video",
            name="bynder_id_hash",
        ),
        migrations.RemoveField(
            model_name="video",
            name="bynder_original_filename",
        ),
        migrations.RemoveField(
            model_name="video",
            name="metadata",
        ),
        migrations.AddField(
            model_name="customdocument",
            name="original_filesize",
            field=models.IntegerField(
                editable=False, null=True, verbose_name="original filesize"
            ),
        ),
        migrations.AddField(
            model_name="customdocument",
            name="source_filename",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=255,
                verbose_name="source filename",
            ),
        ),
        migrations.AddField(
            model_name="customimage",
            name="original_filesize",
            field=models.IntegerField(
                editable=False, null=True, verbose_name="original filesize"
            ),
        ),
        migrations.AddField(
            model_name="customimage",
            name="original_height",
            field=models.IntegerField(
                editable=False, null=True, verbose_name="original height"
            ),
        ),
        migrations.AddField(
            model_name="customimage",
            name="original_width",
            field=models.IntegerField(
                editable=False, null=True, verbose_name="original width"
            ),
        ),
        migrations.AddField(
            model_name="customimage",
            name="source_filename",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=255,
                verbose_name="source filename",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="original_filesize",
            field=models.IntegerField(
                editable=False, null=True, verbose_name="original filesize"
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="original_height",
            field=models.IntegerField(
                editable=False, null=True, verbose_name="original height"
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="original_width",
            field=models.IntegerField(
                editable=False, null=True, verbose_name="original width"
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="source_filename",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=255,
                verbose_name="source filename",
            ),
        ),
        migrations.AlterField(
            model_name="customdocument",
            name="bynder_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=36,
                null=True,
                unique=True,
                verbose_name="Bynder asset ID",
            ),
        ),
        migrations.AlterField(
            model_name="customimage",
            name="bynder_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=36,
                null=True,
                unique=True,
                verbose_name="Bynder asset ID",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="bynder_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=36,
                null=True,
                unique=True,
                verbose_name="Bynder asset ID",
            ),
        ),
    ]
