# Generated by Django 5.0.4 on 2024-04-05 16:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0002_remove_customdocument_bynder_id_hash_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customdocument",
            options={"verbose_name": "document", "verbose_name_plural": "documents"},
        ),
        migrations.AlterModelOptions(
            name="video",
            options={"verbose_name": "video", "verbose_name_plural": "videos"},
        ),
    ]
