name: Ruff

on:
  push:
    branches:
      - main
      - 'stable/**'
  pull_request:
    branches: [main]

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Keep in sync with .pre-comit-config.yaml
    - run: python -Im pip install --user ruff==0.4.1

    - name: Run ruff
      working-directory: ./src
      run: ruff --output-format=github wagtail_bynder
